### PR TITLE
Add scatter reduce converters

### PR DESCRIPTION
**Pull request by shivadbhavsar**

### CODE REVIEW

**Review by CharlieL7 — COMMENTED** [review]
There's an extra underscore in the pytorch spec AFAIK: https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html#

**Comment by CharlieL7** [comment]
It also looks like the `scatter_reduce_` operator is in beta in pytorch? https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_reduce_.html

**Comment by shivadbhavsar** [comment]
> There's an extra underscore in the pytorch spec AFAIK: https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html#

So that doc is for the in-place version of this method (ie. the tensor itself is changed). FX graphs don't support in place functions, if you try to write a test case for it, it will fail to trace a module with an explicit in-place call like that (I tried)

**Comment by shivadbhavsar** [comment]
> It also looks like the `scatter_reduce_` operator is in beta in pytorch? https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_reduce_.html

Oh right it is. I have seen the apis change slightly when beta features become stable but usually its not a major change (like in this case they might add another reduction type in a newer release or something). Also, we havent really encountered models that use this explicitly, to me it just made sense to support this and route scatter_add to this because this is essentially a generalized version of that op.

**Review by CharlieL7 — APPROVED** [review]

**Pull request merged**
